<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="freemarker"
    nsURI="http://code.google.com/a/eclipselabs.org/p/mongo-emf/1.0/freemarker" nsPrefix="org.eclipselabs.mongo.freemarker">
  <eClassifiers xsi:type="ecore:EClass" name="FreeMarkerTemplate" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contents" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
